### ISSUE TITLE
Does someone know how to output it without a hash?

### ISSUE THREAD

**Issue by yustinTR** [atlowChemi/vite-svg-2-webfont#19] opened 2024-02-13 12:06 UTC
it outputs them like this :
dist/assets/test-oBK5LLTu.woff2

**Comment by atlowChemi** [comment] 2024-02-22 12:58
That is due to the `guid()` called here: https://github.com/atlowChemi/vite-svg-2-webfont/blob/b14d485ae33afb051620034699119de27b94c67e/src/index.ts#L104

Why do you need to remove the hash? what is the use case?

**Comment by Azarattum** [comment] 2024-02-23 10:23
@atlowChemi for example, I would want to add `<link rel="preload"` for my font. And I cannot do that unless I know the path in advance. Also I would really like an option to inline font assets as base64 (that would totally solve the preload issue for me).

**Comment by atlowChemi** [comment] 2024-03-03 13:32
@Azarattum thank you for your contribution! 🙂 

@yustinTR Does the change added @Azarattum work for your needs?
Still not clear to me what the issue is 🙂

**Comment by atlowChemi** [comment] 2024-03-12 13:50
I'll be closing this as some time has passed, feel free to re-open if needed 🙂

**Closed** 2024-03-12 13:50 UTC
